### ISSUE TITLE
Cannot press back button

### ISSUE THREAD

**Issue by ar1bis** [ixzzd/webogram_8110#2]
When am in a chat and want to go back to the main screen by pressing the back button, I cannot do this without keeping the 'up' key pressed until the message display has scrolled up to the first loaded message (this can take quite a while for long chats). After this happens, it is possible to move the cursor on to the back button.

Is there a way of pressing the back button directly?

**Comment by sunsetsonwheels** [comment]
I believe the Call button is used for going back.

**Comment by ixzzd** [comment]
I faced with the same issue, i will try to fix it

**Comment by ixzzd** [comment]
Now call button works as a back button inside chats
